KEYMAP="./Elil_50/keymap.c"
CONFIG="./Elil_50/config.h"
RULES="./Elil_50/rules.mk"
PS2_VENDOR="./PS2_driver/ps2_vendor.c"
PS2_MOUSE="./PS2_driver/ps2_mouse.c"

TARGET="./qmk_firmware/keyboards/crkbd/keymaps"
PS2_DRIVER_PATH="./qmk_firmware/platforms/chibios/drivers/vendor/RP/RP2040"
PS2_MOUSE_PATH="./qmk_firmware/drivers/ps2"

#rm -r "$TARGET/Elil_50"
#mkdir "$TARGET/Elil_50"
cp "$KEYMAP" "$TARGET/Elil_50"
cp "$CONFIG" "$TARGET/Elil_50"
cp "$RULES" "$TARGET/Elil_50"
cp "$PS2_VENDOR" "$PS2_DRIVER_PATH"
cp "$PS2_MOUSE" "$PS2_MOUSE_PATH" 
